### PR TITLE
Run entrypoint on devfiles published to GitHub pages

### PR DESCRIPTION
**Pull request by ericwill**
### What does this PR do?
Runs `entrypoint.sh` on the devfiles that are published to GitHub pages.

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Part of eclipse/che#19269

### How to test this PR?

Run the `.ci/generate_and_publish_registry_url_devfiles.sh` script and observe that the correct devfile registry URL is substituted into the Quarkus devfile.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
One pr check is failing ?

**Comment by benoitf** [comment]
I think digest is not working for quarkus image as it's a rolling tag

**Comment by ericwill** [comment]
> I think digest is not working for quarkus image as it's a rolling tag

Yep, will fix it in a separate PR. By the way, how do we enable GitHub pages for this repository? It seems it's not enabled at the moment.

**Comment by benoitf** [comment]
to enable it, a bugzilla ticket probably

**Comment by l0rd** [comment]
When the devfiles will be published on github pages, can add a reference to the latest registry URL from `che-devfile-registry` README file?

**Comment by ericwill** [comment]
> When the devfiles will be published on github pages, can add a reference to the latest registry URL from `che-devfile-registry` README file?

Doing it dynamically is tricky because it would require a PR. However we can also publish a `latest` directory and add a link to that in the README.

**Comment by l0rd** [comment]
Ok I think it's useful to have a registry published on github pages that is
always in sync with the main branch and reference that from the README file.

**Comment by benoitf** [comment]
we can have a `main` and a `latest` alias then

**Pull request merged**
