### PR TITLE
fix: better recovery from a failed skopeo...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

fix: better recovery from a failed skopeo inspect -- try again and if not resolved after 2 attempts, DON'T CHANGE the digest to a nullstring

Change-Id: Ic65d99256542b646eb7f3e64f404f40071edab72
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
Avoids this problem:
https://github.com/eclipse-che/che-devfile-registry/pull/526/files#diff-d567d4dc0d879e5b1da3a21d592817871f3651f034a8d3c5d444a18a71ba243eR12

### How to test this PR?

1. Edit this file: ` che-devfiles-registry/dockerfiles/antora-2.3/Dockerfile`
2. set an invalid BASE_IMAGE address like `ARG BASE_IMAGE="docker.io/antora/antFFora:2.3.3"`
3. run `./build/workflows/check-sidecar-image-digests.sh`

After 30 seconds, no change will be applied to the registry and the processing of other Dockerfiles will continue. \o/

To prove that it WILL change when it DOES find a different latest digest:

1. Edit this file: ` che-devfiles-registry/dockerfiles/antora-2.3/Dockerfile`
2. set a different SHA, like `FROM docker.io/antora/antora@sha256:f00barf`
3. run `./build/workflows/check-sidecar-image-digests.sh`

Watch as the file is changed and your bad digest is reverted to a valid one. \o/ 

If you let the script run its course you should see ONE file changed: `dockerfiles/golang-1.17/Dockerfile`

https://github.com/eclipse-che/che-devfile-registry/pull/526/files#diff-8f51fac72ac1fc135355f5eaabe8e7984b6f79048c983e55dd78ca94d040677dR12

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by nickboldt** [comment]
Replaces https://github.com/eclipse-che/che-devfile-registry/pull/526

**Comment by nickboldt** [comment]
Side note: can we get rid of node 10 and move to node 12 or 14? Or even node 16?

https://catalog.redhat.com/software/containers/ubi8/nodejs-16/615aee9fc739c0a4123a87e1

Does the lang server we use in CRW (and presumably Che too) work with newer node, or is it tied to 10?

We're on 0.3.7 - https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-plugin-java8/build/build_node10.sh#L19
Latest is 0.8.1 - https://github.com/typescript-language-server/typescript-language-server/releases/tag/v0.8.1

We're on typescript 3.4.5: https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-plugin-java8/build/build_node10.sh#L18
Latest is 4.5.2: https://www.npmjs.com/package/typescript

**Comment by nickboldt** [comment]
If you approve this, please merge it. The question around node10/12/14/16 can be handled in a separate issue, should we agree it's time to update to the latest TS lang server.

**Review by benoitf — APPROVED** [review]

**Review by svor — APPROVED** [review]
Tested as described in the description, it works as expected. Thanks!

**Comment by svor** [comment]
> Side note: can we get rid of node 10 and move to node 12 or 14? Or even node 16?
> 
> https://catalog.redhat.com/software/containers/ubi8/nodejs-16/615aee9fc739c0a4123a87e1
> 
> Does the lang server we use in CRW (and presumably Che too) work with newer node, or is it tied to 10?
> 
> We're on typescript lang server 0.3.7 - https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-plugin-java8/build/build_node10.sh#L19 Latest is 0.8.1 - https://github.com/typescript-language-server/typescript-language-server/releases/tag/v0.8.1
> 
> We're on typescript 3.4.5: https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-plugin-java8/build/build_node10.sh#L18 Latest is 4.5.2: https://www.npmjs.com/package/typescript

We can try to update node, for now I don't know any problems with it, but it needs to be tested with all samples which required node. 
Also i'm not sure why do we need typescript lang server and typescript in the image, i don't see that these packages are installed in upstream

**Comment by svor** [comment]
@nickboldt I've created an issue for updating Node base image in CRW https://issues.redhat.com/browse/CRW-2527

**Pull request merged**
