### PR TITLE
fix(gh-pages): install yq in next-build job

### PR DESCRIPTION
**Pull request by ericwill**
### What does this PR do?
Installs yq at the end of the next-build GitHub actions job, so that the publish to GitHub actions succeeds.

### What issues does this PR fix or reference?

eclipse/che#19779

### How to test this PR?

Run the next-build GH action job on this PR branch and see that it succeeds.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by benoitf** [comment]
FYI the link is not clickable for the related issue

**Review by benoitf — APPROVED** [review]

**Review by benoitf — COMMENTED** [review]
I would use maybe instead ?


https://github.com/marketplace/actions/yq-portable-yaml-processor

**Comment by ericwill** [comment]
> I would use maybe instead ?
> 
> https://github.com/marketplace/actions/yq-portable-yaml-processor

I tried it last time and couldn't get it working. TBH the script should be re-written to use the other yq (the one we are using elsewhere and in CRW). It's a TODO for me.

**Comment by benoitf** [comment]
you mean
```
- name: yq - portable yaml processor
  uses: mikefarah/yq@v4.9.6
```
is not working ?

**Comment by benoitf** [comment]
maybe it's because we use a go yq v3 and not v4 (now the v4 is like jq and the python yq wrapper to make things simple :D )

**Comment by ericwill** [comment]
> you mean
> 
> ```
> - name: yq - portable yaml processor
>   uses: mikefarah/yq@v4.9.6
> ```
> 
> is not working ?

Yes, last I tried I ran into: https://github.com/mikefarah/yq/issues/418#issuecomment-617272180

**Comment by ericwill** [comment]
> maybe it's because we use a go yq v3 and not v4 (now the v4 is like jq and the python yq wrapper to make things simple :D )

Yes, it's a TODO to re-write it for v3 :smile:

**Comment by benoitf** [comment]
so let's merge

**Pull request merged**
