### PR TITLE
chore: update to latest...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore: update to latest @eclipse-che/che-theia-devworkspace-handler@0.0.1-1638274327 (should this be done automatically?)

Change-Id: I493204202687573673663b8619f2614c70bdce96
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit message above for issue number)

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by nickboldt** [comment]
do we have a process in place to ensure devfile reg pulls the latest version? 

https://www.npmjs.com/package/@eclipse-che/che-theia-devworkspace-handler

Asking because when I build the devfile reg locally I see this prompt on console, which suggests we have `npm` installed an older version than what `npx` is using:

```
STEP 9: RUN ./generate_devworkspace_templates.sh
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 121 packages, and audited 122 packages in 15s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 8.1.0 -> 8.2.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.2.0
npm notice Run npm install -g npm@8.2.0 to update!
npm notice 
Need to install the following packages:
  @eclipse-che/che-theia-devworkspace-handler
Ok to proceed? (y) y
```

**Review by benoitf — COMMENTED** [review]
I'm not sure it would fix your issue

**Review by benoitf — COMMENTED** [review]
` yes | npm install `

**Comment by nickboldt** [comment]
Do you mean instead of hardcoding version we just use

```
npm install -g @eclipse-che/che-theia-devworkspace-handler
```

to install latest? 

or do you mean:

```
echo y | npm install -g @eclipse-che/che-theia-devworkspace-handler
```
?

**Review by svor — APPROVED** [review]

**Comment by nickboldt** [comment]
@svor if you like this change, please merge it. If you prefer something else (as per Florent's suggestion?) let me know and I can revise the PR or submit a second one.

**Comment by svor** [comment]
As for me it's better to use a fixed version in the script

**Pull request merged**
